#!/bin/sh

## from  https://github.com/spikegrobstein/fzf-menu
## acts like a dmenu

IFS=':'

get_selection() {
  for p in $PATH; do
    ls "$p"
  done \
    | fzf
}

if selection=$( get_selection ); then
  exec "$selection"
fi
