#!/bin/bash

# VARIABLES (change these settings to your liking)
# =====================================
# destination of screencast videos
DESTINATION="$HOME/Videos/Screencasts"
WIN_FULL=$(xwininfo -root | grep 'geometry' |awk '{print $2;}') # record fullscreen
#
STOP="Ctrl+c"
# =====================================
while true
do
clear
echo "============================"
echo "Choice Menu -----"
echo -e "\n"
echo "Enter 1 for WITH-AUDIO 1: "
echo "Enter 2 for NO-AUDIO 2: "
echo "Enter q to exit q: "
echo -e "\n"
echo -e "Enter Choice >\c"
read answer
case "$answer" in
1) 
                sleep 3
                ffmpeg -f alsa -i pulse -f x11grab  -s $WIN_FULL -framerate 24 -i :0.0 -vcodec libx264 -preset ultrafast -crf 0 -threads 0 -y $DESTINATION/screencast.mkv
                #ffmpeg -f alsa -ac 2 -i pulse -f x11grab -r 30 -s $WIN_FULL -i :0.0 -acodec pcm_s16le -vcodec libx264 -preset ultrafast -crf 0  -y $DESTINATION/screencast.mkv
                sleep 4
                spacefm $DESTINATION
                ;;
2) 
				INFO=$(xwininfo -frame)
                WIN_GEOMETRY=$(echo "$INFO"|grep -e "Height:" -e "Width:"|cut -d\: -f2|tr "\n" " "|awk '{print $1 "x" $2}')
                WIN_POSITION=$(echo "$INFO"|grep "upper-left"|head -n 2|cut -d\: -f2|tr "\n" " "|awk '{print $1 "," $2}')
                sleep 3
                ffmpeg -f x11grab  -s $WIN_GEOMETRY -framerate 24 -i :0.0+$WIN_POSITION -vcodec libx264 -preset ultrafast -crf 0 -y $DESTINATION/screencast.mkv
                sleep 4
                spacefm $DESTINATION
                ;;
q) exit ;;
esac
echo -e "enter return to continue \c"
read input
done

