#!/usr/bin/env bash

# Have commented out all the LABELS as they are not needed !
#declare -A LABELS
declare -A COMMANDS
browser='chromium --disk-cache-dir=/tmp/cache'
###
# List of defined 'bangs'
# ALL below are working DK
# Dont need to use ; in front if you dont want
###
# below type rr to use rofi like dmenu to show apps

COMMANDS["rr"]="rofi -show run \"\${input}\""
#LABELS["rr"]="rofi-run"

####################################
#---NOT WORKING SECTION -------------------------###
#COMMANDS[";sr-dmenutest"]=" '/home/dka/bin/rofi-scripts/sr-dmenutest' \"\${input}\""
#LABELS[";sr-dmenutest"]=""
#

#---END OF NOT WORKING SECTION --------------###
####################################

# make sure after the square bracket to leave no space between it and the = i.e. COMMANDS[bla]=
# below working

COMMANDS["todo"]=" '/home/delboy/.bin/rofi-scripts/todo.sh'"
#LABELS["todo"]="todo"

COMMANDS["vtodo"]="mousepad  '/home/delboy/.rofinotes/rofi_todo'"

COMMANDS["vdiary"]="'/home/delboy/.bin/vimdiary'"

# SEARCHES ####
COMMANDS["gs"]="$browser  www.google.com/search?q=\  \" \${input}\""

COMMANDS["mvs"]="$browser http://www.imdb.com/find?q=\" \${input}\""

COMMANDS["yts"]="$browser https://www.youtube.com/results?search_query=\  \" \${input}\""
### 



COMMANDS["edit-rofibangs"]="geany  '/home/delboy/.bin/rofi-scripts/rofi-bangs'"
#LABELS["edit-rofibangs"]=""

COMMANDS["qutebrowser"]="qutebrowser"
#LABELS["qutebrowser"]="qutebrowser"

COMMANDS[".bin"]="pcmanfm '/home/delboy/.bin'"
#LABELS[".bin"]=".bin"



# WEB SITES but can type rb to use rofi-bookmarks script that has more in the list than these few
COMMANDS["weer"]="chromium --disk-cache-dir=/tmp/cache http://www.buienradar.nl/weer/huizen/nl/2753468/3uurs"
#LABELS["weer"]=



#####################################
# putting a # in front of the ones that call scripts

#for password retrieval	
COMMANDS["#snippypw"]=" '/home/dka/bin/rofi-scripts/snippypw'"
#LABELS["#snippypw"]=""

COMMANDS["#screenshot"]='/home/dka/bin/screenshot-scripts/myscreenshot.sh'
#LABELS["#screenshot"]="screenshot"

COMMANDS["#editconfigs"]='/home/dka/bin/edit-configs-and-scripts'
#LABELS["#editconfigs"]="edit"

COMMANDS["#mounttemple"]='echo 0downy | encfs -S /media/ElementsA/new-temple/.new-temple_encfs /media/ElementsA/templemount/'
#LABELS["#mounttemple"]="#mounttemple"

COMMANDS["#unmounttemple"]='fusermount -u  /media/ElementsA/templemount'
#LABELS["#unmounttemple"]="#unmounttemple"



################################################################################
# do not edit below
################################################################################

##
# Generate menu
##
function print_menu()
{
    for key in ${!COMMANDS[@]}
    do
		echo "$key    ${COMMANDS}"
     #   echo "$key    ${LABELS[$key]}"
     # my top version just shows the first field in labels row, not two words side by side
    done
}
##
# Show rofi.
##
function start()
{
    print_menu | rofi -dmenu -p "?=>" 
}


# Run it
value="$(start)"

# Split input.
# grab upto first space.
choice=${value%%\ *}
# graph remainder, minus space.
input=${value:$((${#choice}+1))}

##
# Cancelled? bail out
##
if test -z ${choice}
then
    exit
fi

# check if choice exists
if test ${COMMANDS[$choice]+isset}
then
    # Execute the choice
    eval echo "Executing: ${COMMANDS[$choice]}"
    eval ${COMMANDS[$choice]}
else
	eval  $choice | rofi
 # prefer my above so I can use this same script to also launch apps like geany or leafpad etc (DK)	
 #   echo "Unknown command: ${choice}" | rofi -dmenu -p "error"
fi
