#! /usr/bin/bash
#type noter for a general note
#type noter hobbies  to add a note in the category "hobbies"

_date=$(date "+%Y-%m-%d %H:%M")

category=$1

if [[ -z $category ]]; then
    category="general"
fi

echo "Type Your Note Please:"
read note

if [[ ! -z "${note// }" ]]; then
    echo "$_date => $note [$category]" >> ~/noter_notes.txt
    echo "Your Note: $note [is saved]"
else
    echo " You did not give me a note."
fi
#for checking the notes you can use this script
#!/bin/sh
#
#if [ -z $1 ]
#then
#	tac ~/noter_notes.txt
#	exit 1
#else
#	grep -i "$*" ~/noter_notes.txt
#fi
# call teh script sn and callit likethis
# sn beer (this will output all notes iwth beer)
# sn shows all with most recent first
