#!/bin/bash
#Working

CMD=$(echo "logout
poweroff
suspend
reboot" | eval rofi -dmenu -p "choose")


if [ $? -eq 0 ]; then
   if [ "$CMD" == logout ];then
      i3 exit
   else
      systemctl $CMD
   fi
fi
