#!/bin/bash
#This script IS working, I just wasn't  calling it with the full path ie  '/home/dka/bin/rofi-scripts/rofi-progs'

CMD=$(echo "leafpad
keepassx
halifax-pass
pulseout 'chromium usbspeakers'
halifax-user" | eval rofi -dmenu -p "choose")



#=========
if [ $? -eq 0 ]; then
   if [ "$CMD" == poo ];then
      i3 exit
   else
      xargs $CMD
   fi
fi
#====
# here using the if statements you can perform the required  operation
#if [ "$CMD" = "weather" ]; then
#    chromium www.weer.nl

#elif [ "$options" = "leafpad" ]; then
#    leafpad

#elif [ "$options" = "option3" ]; then
#        echo "You have selected $options"

#elif [ "$options" = "quit" ]; then
#        echo "You have selected $options"
#    exit

# if something else is selected, show the menu again
#else
#    clear;
#    echo "please select some options"

#fi
#done
