#!/bin/bash
# name of script  yt22
DESTINATION="~/YouTube/%(title)s.%(ext)s"
#
echo "highlight the url in browsers bar first"  | rofi -dmenu -p "please press ENTER"
# 
youtube-dl --continue --format 22 -o "${DESTINATION}" `xclip -o`


exit
